export const currentUser = {
  id: "user_1",
  name: "Elizabeth Ling",
  email: "demo@mymind.com",
  image: null,
  plan: "FREE" as const,
  isPro: false,
};

export const itemTypes = [
  {
    id: "type_snippet",
    name: "Snippet",
    slug: "snippet",
    icon: "Code",
    color: "#2563eb",
    softBg: "#eff6ff",
    borderColor: "#bfdbfe",
    contentType: "TEXT" as const,
    isSystem: true,
    isProOnly: false,
  },
  {
    id: "type_prompt",
    name: "Prompt",
    slug: "prompt",
    icon: "Sparkles",
    color: "#7c3aed",
    softBg: "#f5f3ff",
    borderColor: "#ddd6fe",
    contentType: "TEXT" as const,
    isSystem: true,
    isProOnly: false,
  },
  {
    id: "type_note",
    name: "Note",
    slug: "note",
    icon: "StickyNote",
    color: "#ca8a04",
    softBg: "#fefce8",
    borderColor: "#fde68a",
    contentType: "TEXT" as const,
    isSystem: true,
    isProOnly: false,
  },
  {
    id: "type_command",
    name: "Command",
    slug: "command",
    icon: "Terminal",
    color: "#ea580c",
    softBg: "#fff7ed",
    borderColor: "#fed7aa",
    contentType: "TEXT" as const,
    isSystem: true,
    isProOnly: false,
  },
  {
    id: "type_link",
    name: "Link",
    slug: "link",
    icon: "Link",
    color: "#059669",
    softBg: "#ecfdf5",
    borderColor: "#a7f3d0",
    contentType: "URL" as const,
    isSystem: true,
    isProOnly: false,
  },
  {
    id: "type_file",
    name: "File",
    slug: "file",
    icon: "FileText",
    color: "#64748b",
    softBg: "#f8fafc",
    borderColor: "#e2e8f0",
    contentType: "FILE" as const,
    isSystem: true,
    isProOnly: true,
  },
  {
    id: "type_image",
    name: "Image",
    slug: "image",
    icon: "Image",
    color: "#db2777",
    softBg: "#fdf2f8",
    borderColor: "#fbcfe8",
    contentType: "IMAGE" as const,
    isSystem: true,
    isProOnly: true,
  },
];

export const collections = [
  {
    id: "col_react_patterns",
    name: "React Patterns",
    slug: "react-patterns",
    description: "Hooks, components, and composition",
    isFavorite: true,
    itemCount: 12,
  },
  {
    id: "col_ai_prompts",
    name: "AI Prompts",
    slug: "ai-prompts",
    description: "System messages and reusable prompts",
    isFavorite: true,
    itemCount: 8,
  },
  {
    id: "col_sql_admin",
    name: "SQL Admin Scripts",
    slug: "sql-admin-scripts",
    description: "Maintenance, migrations, and analytics queries",
    isFavorite: false,
    itemCount: 6,
  },
  {
    id: "col_saas_boilerplate",
    name: "SaaS Boilerplate",
    slug: "saas-boilerplate",
    description: "Auth, billing, and project scaffolding",
    isFavorite: false,
    itemCount: 9,
  },
  {
    id: "col_interview_prep",
    name: "Interview Prep",
    slug: "interview-prep",
    description: "Algorithms, system design, and notes",
    isFavorite: false,
    itemCount: 14,
  },
  {
    id: "col_context_files",
    name: "Context Files",
    slug: "context-files",
    description: "Saved as references for an active project",
    isFavorite: false,
    itemCount: 5,
  },
];

export const items = [
  {
    id: "item_use_debounce",
    title: "useDebounce hook",
    description: "A debouncing value with a configurable delay",
    itemTypeId: "type_snippet",
    contentType: "TEXT" as const,
    content:
      "import { useEffect, useState } from 'react';\n\nexport function useDebounce<T>(value: T, delay = 300): T {\n  const [debounced, setDebounced] = useState(value);\n\n  useEffect(() => {\n    const id = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(id);\n  }, [value, delay]);\n\n  return debounced;\n}",
    url: null,
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    collectionIds: ["col_react_patterns"],
    tags: ["react", "hook", "performance"],
    lastUsedAt: "2026-06-15T10:24:00.000Z",
    createdAt: "2026-05-02T09:00:00.000Z",
    updatedAt: "2026-06-15T10:24:00.000Z",
  },
  {
    id: "item_code_review_prompt",
    title: "Code review prompt",
    description: "Structured prompt for thorough, actionable code reviews",
    itemTypeId: "type_prompt",
    contentType: "TEXT" as const,
    content:
      "You are a senior engineer reviewing a pull request. Focus on correctness, readability, and edge cases. Provide specific, actionable feedback grouped by severity.",
    url: null,
    language: null,
    isFavorite: true,
    isPinned: true,
    collectionIds: ["col_ai_prompts"],
    tags: ["review", "ai", "engineering"],
    lastUsedAt: "2026-06-14T16:10:00.000Z",
    createdAt: "2026-04-18T13:30:00.000Z",
    updatedAt: "2026-06-14T16:10:00.000Z",
  },
  {
    id: "item_reset_postgres",
    title: "Reset local Postgres",
    description: "One-line script that resets your local development database",
    itemTypeId: "type_command",
    contentType: "TEXT" as const,
    content: "dropdb mymind_dev && createdb mymind_dev && npx prisma migrate deploy",
    url: null,
    language: "bash",
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col_sql_admin"],
    tags: ["postgres", "dev", "reset"],
    lastUsedAt: "2026-06-13T08:45:00.000Z",
    createdAt: "2026-03-22T11:15:00.000Z",
    updatedAt: "2026-06-13T08:45:00.000Z",
  },
  {
    id: "item_auth_setup",
    title: "NextAuth v5 setup",
    description: "Baseline Auth.js config with GitHub provider and Prisma adapter",
    itemTypeId: "type_snippet",
    contentType: "TEXT" as const,
    content:
      "import NextAuth from 'next-auth';\nimport GitHub from 'next-auth/providers/github';\nimport { PrismaAdapter } from '@auth/prisma-adapter';\nimport { prisma } from '@/lib/db';\n\nexport const { auth, handlers, signIn, signOut } = NextAuth({\n  adapter: PrismaAdapter(prisma),\n  providers: [GitHub],\n});",
    url: null,
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col_saas_boilerplate"],
    tags: ["auth", "nextauth", "boilerplate"],
    lastUsedAt: "2026-06-10T14:00:00.000Z",
    createdAt: "2026-05-20T09:30:00.000Z",
    updatedAt: "2026-06-10T14:00:00.000Z",
  },
  {
    id: "item_two_sum",
    title: "Two Sum — hash map approach",
    description: "Classic interview problem solved with a single-pass hash map",
    itemTypeId: "type_note",
    contentType: "TEXT" as const,
    content:
      "Walk the array once, storing each value's index in a map. For each value `n`, check if `target - n` already exists in the map.\n\nTime: O(n)\nSpace: O(n)",
    url: null,
    language: null,
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col_interview_prep"],
    tags: ["algorithms", "hashmap", "interview"],
    lastUsedAt: "2026-06-09T20:00:00.000Z",
    createdAt: "2026-02-11T18:45:00.000Z",
    updatedAt: "2026-06-09T20:00:00.000Z",
  },
  {
    id: "item_prisma_docs",
    title: "Prisma Migrate docs",
    description: "Official guide for creating and applying migrations",
    itemTypeId: "type_link",
    contentType: "URL" as const,
    content: null,
    url: "https://www.prisma.io/docs/orm/prisma-migrate/getting-started",
    language: null,
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col_saas_boilerplate"],
    tags: ["prisma", "docs", "migrations"],
    lastUsedAt: "2026-06-08T12:30:00.000Z",
    createdAt: "2026-05-30T15:00:00.000Z",
    updatedAt: "2026-06-08T12:30:00.000Z",
  },
];
